name: "Pull Request"

on:
    pull_request:
        types: [opened, synchronize]

concurrency:
    # Cancel old runs if there is a new commit in the same branch
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-node:
        uses: ./.github/workflows/build-node.yaml
        secrets: inherit
    build-browser:
        uses: ./.github/workflows/build-browser.yaml
        secrets: inherit
